FROM oven/bun:1

WORKDIR /frontend

COPY package.json bun.lockb ./

RUN bun install

COPY . .

RUN GENERATE_SOURCEMAP=false bunx --bun vite build

FROM nginx:1.20-alpine

COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf

COPY --from=build-stage /frontend/dist /usr/share/nginx/html

EXPOSE 3000