# Build stage
FROM maven:3.8.5-openjdk-17 AS build

WORKDIR /backend

COPY . .

RUN mvn clean install -DskipTests

# Package stage
FROM openjdk:17-jdk-alpine

COPY --from=build /backend/target/*.jar /app.jar

EXPOSE 8080

CMD java -jar /app.jar