name: Continous Deployment

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push
      uses: docker/bake-action@v3
      with:
        push: true
        files: ./proj_CountMeIn/compose.yml
        set: |
          *.cache-to=type=gha,scope=cached-stage,mode=max
          *.cache-from=type=gha,scope=cached-stage
  
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Deploy with Docker Compose
      run: |
        docker-compose -f ./proj_CountMeIn/compose.yml pull
        docker-compose -f ./proj_CountMeIn/compose.yml up -d --remove-orphans
        docker container prune -f
        docker image prune -af
        docker builder prune
